mysite/home/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='homepage'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^(?P<username_id>[0-9]+)/$', views.profile, name='profile'),

    url(r'^view/accept/', views.offerAccept, name='offerAccept'),
    url(r'^view/reject/', views.offerReject, name='offerReject'),
    url(r'^view/', views.viewOffer, name='viewOffer'),
    url(r'^offer/cancel/', views.DeleteOffer, name='cancelOffer'),
    url(r'^offer/', views.OfferCreateView.as_view(), name='offer'),

    url(r'^login/', views.LoginFormView.as_view(), name='login'),

    url(r'^logout/', views.logout, name='logout'),

    url(r'^admin/', admin.site.urls),

    # add an item
    url(r'^item/add/$', views.ItemCreate.as_view(success_url="/home/"), name='item-add'),

    # update an item
    url(r'item/(?P<pk>[0-9]+)/$', views.ItemUpdate.as_view(), name='item-update'),

    # url(r'^(?P<username_id>[0-9]+)/$', views.ItemCreate.as_view(), name='item-add'),

    # delete an item
    # url(r'item/(?P<pk>[0-9]+)/delete/$', views.ItemDelete.as_view(), name='item-delete'),

]

# urlpatterns = [
#     url(r'^$', views.HomeView.as_view(), name='home'),
#
#     url(r'^(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name='profile'),
#
#     # url(r'^home/add/$', views.ProfileView.as_view(), name='item-add'),
# ]







mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include('home.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/home/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone


class User(models.Model):
    username = models.CharField(max_length=21)
    password = models.CharField(max_length=26)
    name = models.CharField(max_length=100)
    degree = models.CharField(max_length=100, blank=True, help_text='Leave blank if personnel/faculty')
    office = models.CharField(max_length=100, blank=True, help_text='Leave blank if student')

    def get_absolute_url(self):
        return reverse('home:homepage', kwargs={'pk': self.pk})

    def __str__(self):
        return self.username

item_Type = (
    ('Academic Use', 'Academic Use'),
    ('Office Use', 'Office Use'),
)


class Item(models.Model):
    userName = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(primary_key=True, max_length=300)
    photo = models.FileField()
    quantity = models.PositiveIntegerField(default=1)
    condition = models.CharField(max_length=200)
    itemType = models.CharField(max_length=100, choices=item_Type, default='Academic Use')
    courseName = models.CharField(max_length=100, blank=True, help_text='Leave blank if Office Use')
    pub_date = models.DateTimeField('date published')

    # def choice(self):
    #     if self.

    # def get_absolute_url(self):
    #     return reverse('home:homepage', kwargs={'pk': self.pk})
    #
    # def __str__(self):
    #     return self.name


class Tags(models.Model):
    name = models.ForeignKey(Item, on_delete=models.CASCADE)
    tag = models.CharField(max_length=100)

    def __str__(self):
        return self.tag

class Offer(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='itemBuy')
    offerer = models.ForeignKey(User, on_delete=models.CASCADE)
    accept = models.BooleanField(default=False)
    reject = models.BooleanField(default=False)
    itemO = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='itemOffer', null=True, blank=True)
    cashO = models.PositiveIntegerField(default=0)
    message = models.TextField(default="")

mysite/home/forms.py
from django import forms
from .models import User, Item, Offer


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'name', 'degree', 'office']

class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']

class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ['itemO', 'cashO', 'message']

        labels = {
            'itemO': 'Item Offer',
            'cashO': 'Cash Offer',
        }

    def __init__(self, user=None, *args, **kwargs):
        super(OfferForm, self).__init__(*args, **kwargs)
        if user is not None:
            try:
                user = User.objects.get(id=user)

                try:
                    items = Item.objects.filter(userName=user)
                    self.fields['itemO'] = forms.ModelChoiceField(queryset=items, widget=forms.Select(attrs={'required': False}),
                                                                  label='Item Offer', required=False)
                    self.fields['itemO'].label_from_instance = lambda obj: "%s" % obj.name
                except Item.DoesNotExist:
                    pass
            except User.DoesNotExist:
                pass

mysite/home/views.py
from django.core.paginator import Paginator, Page, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.shortcuts import render, get_object_or_404
from .models import User, Item, Tags, Offer
from .forms import UserForm, LoginForm, OfferForm


def home(request):
    limit = 10
    latest_item_list = Item.objects.order_by('-pub_date')
    latest_tag_list = Tags.objects.all()

    paginator = Paginator(latest_item_list, limit)
    paginatorT = Paginator(latest_tag_list, limit)
    pageNum = 1
    page = paginator.page(1)
    pageT = paginatorT.page(1)

    if 'page' in request.GET:
        pageNum = int(request.GET['page'])
        try:
            page = paginator.page(pageNum)
            pageT = paginatorT.page(pageNum)
        except PageNotAnInteger:
            page = paginator.page(1)
            pageT = paginatorT.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
            pageT = paginatorT.page(paginator.num_pages)

    context = {'latest_item_list': page,
               'latest_tag_list': pageT,
               'page': pageNum,
               }
    return render(request, 'home/home.html', context)


def profile(request, username_id):
    user = get_object_or_404(User, pk=username_id)
    latest_item_list = Item.objects.order_by('-pub_date')
    latest_tag_list = Tags.objects.all()
    context = {'user': user,
               'latest_item_list': latest_item_list,
               'latest_tag_list': latest_tag_list,
               }
    return render(request, 'home/profile.html', context)


class ItemCreate(CreateView):
    model = Item
    fields = ['userName', 'name', 'photo', 'quantity', 'condition', 'itemType', 'courseName', 'pub_date']

# def ItemCreate(ModelForm):
#
#     class Meta:
#         model = Item

class OfferCreateView(View):
    form_class = OfferForm
    template_name = 'home/offer.html'

    def get(self, request):
        # Offer.objects.all().delete()
        if 'user' in request.session and 'post' in request.GET:
            offer = None
            user = User.objects.get(id=request.session['user'])
            try:
                offer = Offer.objects.get(offerer=user)
                self.form_class = self.form_class = OfferForm(instance=offer, user=request.session['user'])
            except Offer.DoesNotExist:
                self.form_class = OfferForm(user=request.session['user'])

            return render(request, self.template_name, {'form': self.form_class, 'offer': offer})
        else:
            return HttpResponseRedirect('/home/')

    def post(self, request):
        if 'user' in request.session:
            try:
                item = Item.objects.get(name=request.POST['item'])
                user = User.objects.get(id=request.session['user'])

                try:
                    offer = Offer.objects.get(item=item, offerer=user)
                    form = OfferForm(data=request.POST, instance=offer)

                    if form.is_valid():
                        form.save()
                    else:
                        return render(request, self.template_name, {'form': form})
                except Offer.DoesNotExist:
                    offer = OfferForm(data=request.POST)

                    if offer.is_valid():
                        offer = offer.save(commit=False)
                        offer.item = item
                        offer.offerer = user
                        offer.save()
                    else:
                        return render(request, self.template_name, {'form': offer})

                return HttpResponseRedirect('/home/')
            except Item.DoesNotExist:
                return HttpResponseRedirect('/home/')
        else:
            return HttpResponseRedirect('/home/')

def DeleteOffer(request):
    if 'post' in request.GET and 'user' in request.session:
        try:
            user = User.objects.get(id=request.session['user'])
            post = Item.objects.get(name=request.GET['post'])
            offer = Offer.objects.get(item=post, offerer=user)
            offer.delete()

            return HttpResponseRedirect('/home/')
        except User.DoesNotExist or Item.DoesNotExist or Offer.DoesNotExist:
            return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')

class ItemUpdate(UpdateView):
    model = Item
    fields = ['userName', 'name', 'photo', 'quantity', 'condition', 'itemType', 'courseName', 'pub_date']

class ItemDelete(DeleteView):
    model = Item
    success_url = reverse_lazy('home:homepage')

class LoginFormView(View):
    form_class = LoginForm
    template_name = 'home/login.html'

    #display
    def get(self, request):
        form = self.form_class(None)
        if 'user' in request.session:
            return HttpResponseRedirect('/home/')

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            try:
                user = User.objects.get(username=form.cleaned_data['username'], password=form.cleaned_data['password'])

                request.session['user'] = user.id
                return HttpResponseRedirect('/home/')
            except User.DoesNotExist:
                return render(request, self.template_name, {'form': form})

        return render(request, self.template_name, {'form': form})

class UserFormView(View):
    form_class = UserForm
    template_name = 'home/registration_form.html'

    # display a blank form
    def get(self, request):
        if 'user' in request.session:
            return HttpResponseRedirect('/home/')

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # clean (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.password = password
            user.save()

            # returns User objects if correct credentials
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    success_url = reverse_lazy('home:homepage')
                    # return redirect('home:homepage')

            return HttpResponseRedirect('/home/login/')

        return render(request, self.template_name, {'form': form})


def logout(request):
    if 'user' in request.session:
        del request.session['user']
    return HttpResponseRedirect('/home/')


def offerAccept(request):
    if 'offer' in request.GET and 'user' in request.session:
        try:
            offer = Offer.objects.get(id=request.GET['offer'])
            offer.reject = False
            offer.accept = True
            offer.save()

            return HttpResponseRedirect('/home/')
        except Offer.DoesNotExist:
            return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')


def offerReject(request):
    if 'offer' in request.GET and 'user' in request.session:
        try:
            offer = Offer.objects.get(id=request.GET['offer'])
            offer.reject = True
            offer.accept = False
            offer.save()

            return HttpResponseRedirect('/home/')
        except Offer.DoesNotExist:
            return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')


def viewOffer(request):
    if 'user' in request.session and 'post' in request.GET:
        post = Item.objects.get(name=request.GET['post'])

        offers_list = Offer.objects.filter(item=post)
        return render(request, 'home/view.html', {'offers_list': offers_list})
    else:
        return HttpResponseRedirect('/home/')

mysite/home/templates/home/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New Beginnings Marketplace{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css'%}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:homepage' %}">New Beginnings Marketplace</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home:homepage' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:item-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Post an Item
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:register' %}">
                        <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:login' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}

{% endblock %}
</body>
</html>

mysite/home/templates/home/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

mysite/home/templates/home/header.html
<!DOCTYPE html>
<html>
<head>
	<title>New Beginnings Marketplace</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" type = "text/css"/>
	<meta name="viewport" content = "width=device-width, initial-scale=1.0">
	
	<style type="text/css">
		html,
		body {
		  height:100%
		}
	</style>
</head>

<body class="body" style="background-color:#f6f6f6">

<div class="row">

{% if latest_item_list %}
    <h3><center>Home</center></h3>
    {% for item in latest_item_list %}
      <div class="col-md-2">
        <div class="thumbnail">
          <img src="{{ item.photo.url }}" >
          <div class="caption">
            <h3>{{ item.name }} ({{ item.quantity }})</h3>
              <h6><a href="/home/{{ item.userName.id }}/">{{ item.userName }}</a></h6>
            <p>{{ item.condition }}<br/>
              Type: {{ item.itemType }}</p>
          </div>
        </div>
        </div>
    {% endfor %}
{% else %}
    <p>No item available</p>
{% endif %}
        
    </div>    
    
</body>
</html>

mysite/home/templates/home/home.html
{% extends 'home/base_template.html' %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:homepage' %}">New Beginnings Marketplace</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home:homepage' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Post an Item
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:register' %}">
                        <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:login' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}

<body class="body" style="background-color:#f6f6f6">

    <br/>
    <br/>

<div class="container">

{#    {% if all_items %}#}
{#        {% for item in all_items %}#}
    {% if latest_item_list %}
        <div style="text-align: center;"><h3>{{ latest_item_list }}</h3></div>
        {% for item in latest_item_list %}
          <div class="col-md-2">
                <div class="thumbnail">
                    <img src="{{ item.photo.url }}" class="img-thumbnail" />
                     <div class="caption">

                        <h3>{{ item.name }}</h3><h6><a href="{% url 'home:profile' item.userName.id %}">{{ item.userName }}</a></h6>

                        <p>{{ item.condition }}<br/><b>Type: {{ item.itemType }}</b></p>

                         <h6>
                             {% for tags in latest_tag_list %}
                                  {% if tags.itemName.id == item.id %}
                                        #{{ tags.tag }}&nbsp;
                                  {% endif %}
                             {% endfor %}
                         </h6>
                        {% if 'user' in request.session and request.session.user != item.userName.id%}
                             <a href="/home/offer/?post={{ item.pk }}" class="btn btn-block btn-primary">Offer</a>
                        {% elif 'user' in request.session %}
                            <a href="/home/view/?post={{ item.pk }}" class="btn btn-block btn-primary">View Offers</a>
                        {% endif %}

{#                         <form action="{% url 'home:item-delete' item.name.id %}" method="post" style="display: inline;">#}
{#                                {% csrf_token %}#}
{#                                <input type="hidden" name="item_name_id" value="{{ item.name.id }}"/>#}
{#                                <button type="submit" class="btn btn-default btn-sm">#}
{#                                    <span class="glyphicon glyphicon-trash"></span>#}
{#                                </button>#}
{#                         </form>#}

                     </div>
                 </div>
          </div>
        {% endfor %}
    {% else %}
        <p>No item available</p>

    {% endif %}

</div>
    <center>
            <a href="{% url 'home:homepage' %}?page={{ page|add:1 }}"><button type="load" class="btn btn-inverse" style="cursor: pointer !important;">Load More</button></a>
        </center>
</body>

{% endblock %}


mysite/home/templates/home/item_form.html
{%  extends 'home/base_template.html' %}
{% block title %}Add a New Item{% endblock %}
{% block item_active %}active{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>
    </div>

{% endblock %}

mysite/home/templates/home/offer.html
{%  extends 'home/base_template.html' %}
{% block title %}Offer{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-sm-12 col-md-7">
             <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Offer Money/Product</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% if offer is not None %}
                        {% if offer.accept %}
                            <p><strong>Your previous offer was accepted</strong></p>
                        {% elif offer.reject %}
                            <p><strong>Your previous offer was rejected</strong></p>
                        {% else %}
                            <p><strong>The user has not replied to your previous offer</strong></p>
                        {% endif %}
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <input type="hidden" name="item" value="{{ request.GET.post }}">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-3">
                                <button type="submit" class="btn btn-block btn-success">Offer</button>
                            </div>
                            <div class="col-sm-3">
                                <a href="{% url 'home:cancelOffer' %}?post={{ request.GET.post }}" class="btn btn-block btn-warning">Cancel</a>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>
    </div>

{% endblock %}

mysite/home/templates/home/view.html
{% extends 'home/base_template.html' %}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home:homepage' %}">New Beginnings Marketplace</a>
        </div>

        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'home:homepage' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Post an Item
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'home:register' %}">
                        <span class="glyphicon glyphicon-registration-mark" aria-hidden="true"></span>&nbsp; Register
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:login' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Login
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'home:logout' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

{% block body %}

<body class="body" style="background-color:#f6f6f6">

    <br/>
    <br/>

<div class="container">

{#    {% if all_items %}#}
{#        {% for item in all_items %}#}
    {% if offers_list %}
        {% for offer in offers_list %}
          <div class="col-md-2" style="border: 1px solid #e2e2e2; padding: 5px;">
                {% if offer.itemO %}
                    <div class="thumbnail">
                        <img src="{{ offer.itemO.photo.url }}" class="img-thumbnail" />
                         <div class="caption">

                            <p>{{ offer.itemO.condition }}<br/><b>Type: {{ offer.itemO.itemType }}</b></p>
                         </div>
                     </div>
                {% endif %}

                <p><b>Money: </b> Php. {{ offer.cashO }}</p>
                <p><b>Message: </b> {{ offer.message }}</p>
                <h6><b>Offered By: </b><a href="{% url 'home:profile' offer.offerer.id %}">{{ offer.offerer.name }}</a></h6>
                {% if offer.accept == False and offer.reject == False %}
                    <a href="/home/view/accept/?offer={{ offer.id }}" class="btn btn-success">Accept</a>
                    <a href="/home/view/reject/?offer={{ offer.id }}" class="btn btn-warning">Reject</a>
                {% elif offer.accept == True %}
                    <h6><b>Response: </b>Approved</h6>
                    <a href="/home/view/reject/?offer={{ offer.id }}" class="btn btn-warning">Reject</a>
                {% else %}
                    <h6><b>Response: </b>Rejected</h6>
                    <a href="/home/view/accept/?offer={{ offer.id }}" class="btn btn-success">Accept</a>
                {% endif %}
          </div>
        {% endfor %}

    {% else %}
        <p>No offers available</p>

    {% endif %}

</div>

</body>

{% endblock %}
